### ISSUE TITLE
ModuleNotFoundError: No module named 'spacy.en'

### ISSUE THREAD

**Issue by maomaoyuchengzi** [antspy/quantized_distillation#1]
I run "cifar10_test.py ",but the tab tell me "ModuleNotFoundError: No module named 'spacy.en'"

**Comment by antspy** [comment]
I think it has to do with some external packages - I am not sure which one to be honest. Have you installed alle the packages in requirements.txt? 
Also, please post the whole stack trace of the exception to give us more information :)
