### ISSUE TITLE
A question about Absmax quantization functon

### ISSUE THREAD

**Issue by zhoudaquan** [antspy/quantized_distillation#15]
Hi Antspy,

I have a question about the following codes in the quantization function:

norm_scaling = getattr(tensor, norm_to_use)(p=2)

Can I check what is the meaning of p=2? I was thinking the code is equivalent to tensor.max() while I cannot find any doc for the specification of p. Could you please suggest?

**Comment by antspy** [comment]
Hi, 

that just means taking the p norm of the tensor: https://en.wikipedia.org/wiki/Norm_(mathematics)#p-norm

p=2 corresponds to the usual euclidean norm. Note that this is not the same of tensor.max()

**Comment by zhoudaquan** [comment]
> Hi,
> 
> that just means taking the p norm of the tensor: https://en.wikipedia.org/wiki/Norm_(mathematics)#p-norm
> 
> p=2 corresponds to the usual euclidean norm. Note that this is not the same of tensor.max()

Hi,

Thanks for the reply. In that case, I thought the code should be modified to as following:

norm_scaling = getattr(tensor, norm_to_use).norm(p=2)

Since the norm_to_use is specified as "max" for the case of absmax scaling.
