### ISSUE TITLE
How can I verify my model is quantized?

### ISSUE THREAD

**Issue by YYangZiXin** [antspy/quantized_distillation#16]

**Comment by antspy** [comment]
Could you provide more details?

**Comment by YYangZiXin** [comment]
I want to quantize a model(resnet) to 8 bit , so I train a model with
"
model_name = 'resnet_teacher'
teacherModel=ResNet18()
teacherModel.load_state_dict(cifar10Manager.load_model_state_dict(model_name))
#full Precision model has been trained before
model = teacherModel
model_name = 'resnet_quantized8bits'
model_path = os.path.join(cifar10modelsFolder, model_name)
 if not model_name in cifar10Manager.saved_models:
     cifar10Manager.add_new_model(model_name, model_path)
cifar10Manager.train_model(model, model_name=model_name,
                                train_function=convForwModel.train_model,
                                arguments_train_function={'epochs_to_train': epochsToTrainCIFAR,
                                                          'quantizeWeights': True,
                                                          'numBits': 8,
                                                          'bucket_size': 256,
                                                          'quantize_first_and_last_layer':False},
                                train_loader=train_loader, test_loader=test_loader)
"
and the given acc of the trained model is a little higher than the full Precision model (model) .
i want to verify the model weight is quantized to 8 bits, so i use the code
"
q8_name='resnet_distilled_quantized8bits'
q8=ResNet18()
q8.load_state_dict(cifar10Manager.load_model_state_dict(q8_name))
print(q8.layer1[1].conv1.weight)
"
and i find the print weight is not Integers.
So i want to know How can I verify my model is quantized?

**Comment by antspy** [comment]
Hi,

You can check it with the check_right_bits function in quantization/help_functions.py or with get_huffman_encoding_mean_bit_length in the same file. 

Pytorch 0.3 does not support low bit execution, so we never actually save the weights in low precision - they are quantized to points that *could* be represented with 8 bits, but are actually floats.

check_right_bits checks that the tensors can be represented using a certain number of bits.

**Comment by YYangZiXin** [comment]
Thank you!
