### ISSUE TITLE
The model is evaluated after Full precision weight is load.

### ISSUE THREAD

**Issue by YYangZiXin** [antspy/quantized_distillation#17]
In the code conv_forward_model.py The model is evaluated after Full precision weight is load. I think you should quantizeWeights again after all epochs.

**Comment by antspy** [comment]
Hi YYangZiXin, 

Thanks for spotting the mistake! We did as well and we fixed it in another version of the repository, when I uploaded this one I must have forgotten to include the fix.

I suggest to call quantizeWeights at the very end after all training is done and computing the performance of the model then. I remember that fixing the bug did not affect the measured performance that much, but of course that depends on the task.
