### ISSUE TITLE
How is the setting in the ImageNet?

### ISSUE THREAD

**Issue by appleleaves** [antspy/quantized_distillation#3]
Which file do you run to do the experiments as the **cifar10_test.py** and how much is the batch size of the training process?

**Comment by antspy** [comment]
Hi, 

the batch size is set iequal to 25 in the script https://github.com/antspy/quantized_distillation/blob/master/cifar10_test.py#L51

To run it you need to define a folder where to save the dataset and one where to save the models. That you can run it normally with `python cifar10_test.py`

**Comment by appleleaves** [comment]
Sorry, maybe my expression is wrong.
My question is do you have a file like **imagenet_test.py** to train the imagenet.
When I try to run the imagenet, I find that the batch size is undefined in the script [imageNet_distilled.py](https://github.com/antspy/quantized_distillation/blob/master/imageNet_distilled.py)

**Comment by appleleaves** [comment]
([](https://github.com/antspy/quantized_distillation/blob/master/imageNet_distilled.py))

**Comment by antspy** [comment]
Ah, you're right, you need to define batch size in that script. Simply put the line `batch_size = ... `somewhere before the start of the training. I think in my experiments I used batch_size=25 but I don't remember at the moment :)
