### ISSUE TITLE
Where is the quantization implemented?

### ISSUE THREAD

**Issue by iamweiweishi** [antspy/quantized_distillation#5]
Thank you for your excellent contribution. 
I read some of your codes, but I found that the format and the number of the model weights remain the same. The code 'quantize_weights_model(model)' maps the model weights to different scales.
Could you please give me some clues where the model weights are quantized?
Thank you.

**Comment by antspy** [comment]
Hi, 

the quantization functions are defined here: https://github.com/antspy/quantized_distillation/blob/master/quantization/quant_functions.py

> I found that the format and the number of the model weights remain the same

I am not sure I understand what you mean, could you please clarify?
> The code 'quantize_weights_model(model)' maps the model weights to different scales.

Again, I am not sure what you mean. Maybe you are referring to the fact that we use different scaling factors for every bucket in the tensor, as described in the paper; but in that case this is what we expect to happen.
