### ISSUE TITLE
Why do you have to train Cifar10 two times?

### ISSUE THREAD

**Issue by appleleaves** [antspy/quantized_distillation#6]
Notice: The code should be find in cifar10_test.py in line around 190.
In file **cifar10_test.py** you use code     

```
if TRAIN_SMALLER_MODEL:
        for _ in range(2):
```
to train the model twice.
But as I can see, the first get a higher performance for small model 0, with no quantization or distill.
```
smallerModelSpec0 = {'spec_conv_layers': [(75, 5, 5), (50, 5, 5), (50, 5, 5), (25, 5, 5)],
                    'spec_max_pooling': [(1, 2, 2), (3, 2, 2)],
                    'spec_dropout_rates': [(1, 0.2), (3, 0.3), (4, 0.4)],
                    'spec_linear': [500], 'width': 32, 'height': 32}
```
So Why?

**Comment by antspy** [comment]
Hi, 

I believe this was just a residue of some experiments we were running which I forgot to clean up. There is no particular reason to train it twice.
